//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;

    public partial class AOEntities : DbContext
    {
        public AOEntities()
            : base("name=AOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<paquete> paquetes { get; set; }
    
        public virtual ObjectResult<buscarPaquetes_Result> buscarPaquetes(string tienda, string nombre_apellidos, Nullable<int> numero_factura)
        {
            var tiendaParameter = tienda != null ?
                new ObjectParameter("tienda", tienda) :
                new ObjectParameter("tienda", typeof(string));
    
            var nombre_apellidosParameter = nombre_apellidos != null ?
                new ObjectParameter("nombre_apellidos", nombre_apellidos) :
                new ObjectParameter("nombre_apellidos", typeof(string));
    
            var numero_facturaParameter = numero_factura.HasValue ?
                new ObjectParameter("numero_factura", numero_factura) :
                new ObjectParameter("numero_factura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarPaquetes_Result>("buscarPaquetes", tiendaParameter, nombre_apellidosParameter, numero_facturaParameter);
        }
    
        public virtual int PA_delPaquete(Nullable<int> id_paquete)
        {
            var id_paqueteParameter = id_paquete.HasValue ?
                new ObjectParameter("id_paquete", id_paquete) :
                new ObjectParameter("id_paquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delPaquete", id_paqueteParameter);
        }
    
        public virtual int PA_insPaquete(Nullable<int> numero_factura, string nombre_apellidos, string tienda, string articulo, Nullable<System.DateTime> fecha_envio, string estado)
        {
            var numero_facturaParameter = numero_factura.HasValue ?
                new ObjectParameter("numero_factura", numero_factura) :
                new ObjectParameter("numero_factura", typeof(int));
    
            var nombre_apellidosParameter = nombre_apellidos != null ?
                new ObjectParameter("nombre_apellidos", nombre_apellidos) :
                new ObjectParameter("nombre_apellidos", typeof(string));
    
            var tiendaParameter = tienda != null ?
                new ObjectParameter("tienda", tienda) :
                new ObjectParameter("tienda", typeof(string));
    
            var articuloParameter = articulo != null ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(string));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insPaquete", numero_facturaParameter, nombre_apellidosParameter, tiendaParameter, articuloParameter, fecha_envioParameter, estadoParameter);
        }
    
        public virtual int PA_modPaquete(Nullable<int> id_paquete, Nullable<int> numero_factura, string nombre_apellidos, string tienda, string articulo, Nullable<System.DateTime> fecha_envio, string estado)
        {
            var id_paqueteParameter = id_paquete.HasValue ?
                new ObjectParameter("id_paquete", id_paquete) :
                new ObjectParameter("id_paquete", typeof(int));
    
            var numero_facturaParameter = numero_factura.HasValue ?
                new ObjectParameter("numero_factura", numero_factura) :
                new ObjectParameter("numero_factura", typeof(int));
    
            var nombre_apellidosParameter = nombre_apellidos != null ?
                new ObjectParameter("nombre_apellidos", nombre_apellidos) :
                new ObjectParameter("nombre_apellidos", typeof(string));
    
            var tiendaParameter = tienda != null ?
                new ObjectParameter("tienda", tienda) :
                new ObjectParameter("tienda", typeof(string));
    
            var articuloParameter = articulo != null ?
                new ObjectParameter("articulo", articulo) :
                new ObjectParameter("articulo", typeof(string));
    
            var fecha_envioParameter = fecha_envio.HasValue ?
                new ObjectParameter("fecha_envio", fecha_envio) :
                new ObjectParameter("fecha_envio", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modPaquete", id_paqueteParameter, numero_facturaParameter, nombre_apellidosParameter, tiendaParameter, articuloParameter, fecha_envioParameter, estadoParameter);
        }
    
        public virtual ObjectResult<PA_recPaquetes_Result> PA_recPaquetes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recPaquetes_Result>("PA_recPaquetes");
        }
    
        public virtual ObjectResult<PA_recPaquetesXId_Result> PA_recPaquetesXId(Nullable<int> id_paquete)
        {
            var id_paqueteParameter = id_paquete.HasValue ?
                new ObjectParameter("id_paquete", id_paquete) :
                new ObjectParameter("id_paquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recPaquetesXId_Result>("PA_recPaquetesXId", id_paqueteParameter);
        }
    }
}
